### ISSUE TITLE
Crash when placing a tool in crafting grid

### ISSUE THREAD

**Issue by AnonymousPuppy** [Mine-and-blade-admin/Battlegear2#148]
Using forge .1240, a custom modpack, and M&B Battlegear 2 1.0.6.3. Whenever I put a tool in my crafting grid, my client crashes. This happens with ProjectRed's and Mekanism's tools as well. In-game, I was trying to repair my two pickaxes, and as soon as I placed 1 pickaxe in my 2x2 crafting grid, I crashed.

Crash report: http://pastebin.com/AGJxCynb

This issue was also reported here:
https://github.com/aidancbrady/Mekanism/issues/1913 
https://github.com/MrTJP/ProjectRed/issues/667

By reading the first link, I saw a user post that it was this mod causing the crashes, and I removed it and everything worked fine. 

Please fix this ASAP, thank you.

**Comment by GotoLink** [comment]
"Has been determined to be Mekanism issue, roughly it register items in FMLInit stage instead of FMLPreInit. Which is too late and can cause a wide variety of issues.
It is only coincidental that some mods would reveal the problem, due to the complexity of mod loading order."
Reported in Mekanism#1913.
