### ISSUE TITLE
breaking crash report

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Mine-and-blade-admin/Battlegear2#198]
mod breaking crash report
instead of the crash report, one or the other mod, the current is always visible
http://hastebin.com/oripukinoy.avrasm
without mod, crash report corresponds to an error.

**Comment by GotoLink** [comment]
Crash is a Minecraft bug within crash reporter where StackTraceElement#getFileName() results are compared without null checks, while it is possible to be null.
This data is built from native code and is out of this mod reach.
The issue has yet to be reproduced, too.

**Comment by Mario90900** [comment]
I've had this same issue while trying to put a modpack together myself. When Battlegear is installed, the crash reporter fails to handle something, like you pointed out, but it isn't Battlegear that is crashing. You need to induce another crash somewhere else, where you will get the error as seen pasted above, and the crash reporter will fail which makes trying to put a modpack together quite frustrating. Once you remove Battlegear though, the crash reporter handles fine and prints out the expected error log one should get with a proper crashlog. There's not much more evidence we can give for this, because of the issue breaking the one thing that would help locate the issue. There really seems to be a problem with battlegear, so please revisit this and try to induce a crash with other mods.

If you check this link, http://puu.sh/lHhEs/a8faef4a9b.txt , you will see what happened when I was able to reproduce this issue fairly easily. This is the crash log while Battlegear is installed. This crash was caused by Pam's Harvestcraft and NEI Integration (versions of both should be in the puush), when you tried to check any recipe of any block, the game would crash due to NEI Integration being unable to handle the new Pam's recipes. Once you remove Battlegear, as stated by SvEgiiVEteR above, the crash reporter behaves normally and you get a log like this: http://puu.sh/lHhLA/345aa06c6e.txt .

I hope this can help you locate the root of the issue.

**Comment by GotoLink** [comment]
The full crash reports is more helpful for diff making, thank you.
Apparently, the secondary crash report trace (above system settings) is affected
at net.minecraft.client.Minecraft.func_71396_d(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
Those should be "Minecraft.java" located, not "unknown source" which are the null values crashing the reporter.
And since we do patch Minecraft class, this could be a valid issue.
Began investigating.

**Comment by SvEgiiVEteR** [comment]
thank you very much) will check)
