### ISSUE TITLE
[1.8] Sheathed rendering does not apply scale

### ISSUE THREAD

**Issue by coolAlias** [Mine-and-blade-admin/Battlegear2#204]
It seems that rendering sheathed items does not apply the scale set in the model's .JSON file.

The 1.8 pictures were taken using Forge 1.8-11.14.3.1487, so not the recommended 1450. I don't think that should affect this particular issue, but I know after 1460 or so my shield rendering got all mangled, whereas it worked perfectly before. Still haven't fixed it... 1.8 rendering can be a right pain.

1.8 scaled item held in 3rd person:
![1 8-hammer](https://cloud.githubusercontent.com/assets/5303669/11464220/375e1c12-96e1-11e5-8b96-9cf9532b6c1e.png)

1.8 scaled item sheathed on back:
![1 8-sheathed](https://cloud.githubusercontent.com/assets/5303669/11464223/3a860404-96e1-11e5-9b5e-7273587c86dd.png)

1.7.10 scaled item sheathed on back:
![1 7 10-sheathed](https://cloud.githubusercontent.com/assets/5303669/11464219/32b47b48-96e1-11e5-97e2-5c2b45f79b43.png)

**Comment by GotoLink** [comment]
This one is not on Forge.
Because of 1.8 rendering, sheathed items are now rendered by the mod with the only option available of: "ItemCameraTransforms.TransformType.NONE", or they would be translated, rotated using json values possibly out of the player model (since no longer any control of it on our side). Scaling is indeed affected. An horrible oversight on my part, for sure.
With what I have in mind, I fear the appropriate fix is going to be terrible on performance.

**Comment by coolAlias** [comment]
Bummer :\ I wouldn't call it a horrible oversight... it was just something I noticed, so I figured I'd bring it up in case you weren't aware of it yet.

**Comment by GotoLink** [comment]
Solved for build 1450. Let's hope that last a bit.
Please reopen if necessary.
