### ISSUE TITLE
I can't switch back to the normal hotbar

### ISSUE THREAD

**Issue by Exdaninja** [Mine-and-blade-admin/Battlegear2#220]
Hey i've downloaded your mod but it doesn't seem to switch back when i try to press R again.
I created a server with my friends and they work fine but mine doesn't seem to work properly.
Thanks in advance if u can help me :) By the way I installed your mod with a mod pack which is Natural Magic, It sometimes works but most of the time it doesn't

**Comment by mk-sco** [comment]
I may be late to this, but I get this issue often, don't know the repro for it yet to do a proper report,will work on that... the fix however (for me) is to remove everything from both your vanilla hotbar and your 6 M&B hotbar slots then try again... (so that all hud inventory slots are empty, your 'e' inventory slots don't really matter, you can empty everything into there if you like.

**Comment by SneakTrap** [comment]
Maybe your key for battlemode is conflicting with something?
